spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/vaultcore_db
    username: postgres
    password: pg54321
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false

server:
  port: 8080
